version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "8.3"
    labels: ["dependencies"]
    commit-message:
      prefix: "ci"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "8.1"
    labels: ["dependencies"]
    commit-message:
      prefix: "ci"
      include: "scope"
