from typing import Optional, Union

from java.io import Closeable
from java.lang import Exception, Object
from java.lang import Throwable as Throwable
from java.nio.charset import Charset as Charset

class Plaintext(Object, Closeable):
    def __init__(self) -> None: ...
    def clear(self) -> None: ...
    def close(self) -> None: ...
    @staticmethod
    def fromBytes(bytes: bytearray) -> Plaintext: ...
    @staticmethod
    def fromString(
        str: Union[str, unicode], charset: Optional[Charset] = ...
    ) -> Plaintext: ...
    def getAsString(self) -> Union[str, unicode]: ...
    def getBytes(self) -> bytearray: ...

class SecretException(Exception):
    def __init__(self, message: str, cause: Optional[Throwable] = ...) -> None: ...
