from typing import Any, List, Mapping, Optional, Union

from java.util import Date
from org.python.core import PyObject, PyTuple

class PyResource(PyObject):
    def __init__(self, resource: Any = ...) -> None: ...
    def getCollection(self) -> Union[str, unicode]: ...
    def getDefiningCollection(self) -> Union[str, unicode]: ...
    def getName(self) -> Optional[Union[str, unicode]]: ...
    def getResourceType(self) -> PyTuple: ...
    def getDocumentation(self) -> Optional[Union[str, unicode]]: ...
    def getFiles(self) -> Mapping[Union[str, unicode], Any]: ...
    def getFile(self, key: Union[str, unicode]) -> Any: ...
    def getConfig(self) -> Any: ...
    def getBackupConfig(self) -> Any: ...
    def getFileNames(self) -> List[Union[str, unicode]]: ...
    def getAttributes(self) -> PyObject: ...
    def getAttribute(self, key: Union[str, unicode]) -> PyObject: ...
    def getId(self) -> Optional[Union[str, unicode]]: ...
    def getLastModificationActor(self) -> Optional[Union[str, unicode]]: ...
    def getLastModificationTime(self) -> Optional[Date]: ...
    def getResource(self) -> Any: ...
    def isEnabled(self) -> bool: ...
    def isSingleton(self) -> bool: ...
