from typing import Union

from com.inductiveautomation.ignition.common.script.abc import ContextManager
from com.inductiveautomation.ignition.gateway.secrets import Plaintext
from java.lang import Record

class PyPlaintext(ContextManager):
    def __init__(self, plaintext: Plaintext) -> None: ...
    def clear(self) -> None: ...
    def getSecretsAsBytes(self) -> bytearray: ...
    def getSecretsAsString(
        self, charsetName: Union[str, unicode, None] = ...
    ) -> Union[str, unicode]: ...

class SecretMeta(Record):
    def __init__(self, name: Union[str, unicode]) -> None: ...
    def name(self) -> Union[str, unicode]: ...

class SecretProviderMeta(Record):
    def __init__(
        self,
        name: Union[str, unicode],
        description: Union[str, unicode],
        type_: Union[str, unicode],
    ) -> None: ...
    def description(self) -> Union[str, unicode]: ...
    def name(self) -> Union[str, unicode]: ...
    def type(self) -> Union[str, unicode]: ...
