from typing import Any, Dict, List, Union

from com.inductiveautomation.ignition.common.secrets import (
    PyPlaintext,
    SecretMeta,
    SecretProviderMeta,
)
from org.python.core import PyObject

def createEmbeddedSecretConfig(json: Any) -> PyObject: ...
def createReferencedSecretConfig(
    providerName: Union[str, unicode], secretName: Union[str, unicode]
) -> PyObject: ...
def decrypt(json: Any) -> PyPlaintext: ...
def encrypt(*args: Any) -> Dict[Union[str, unicode], Any]: ...
def getProviders() -> List[SecretProviderMeta]: ...
def getSecrets(providerName: Union[str, unicode]) -> List[SecretMeta]: ...
def readConfiguredSecretValue(secretConfig: Any) -> PyPlaintext: ...
def readSecretValue(
    providerName: Union[str, unicode], secretName: Union[str, unicode]
) -> PyPlaintext: ...
