from typing import Any, Dict, List, Union

from com.inductiveautomation.ignition.common.secrets import (
    PyPlaintext,
    SecretMeta,
    SecretProviderMeta,
)

def decrypt(json: Any) -> PyPlaintext: ...
def encrypt(*args: Any) -> Dict[Union[str, unicode], Any]: ...
def getProviders() -> List[SecretProviderMeta]: ...
def getSecrets(providerName: Union[str, unicode]) -> List[SecretMeta]: ...
def readSecretValue(
    providerName: Union[str, unicode], secretName: Union[str, unicode]
) -> PyPlaintext: ...
