name: ci

on:
  push:
    branches:
      - '8.3'
  pull_request:
    branches:
      - '8.3'

jobs:
  pre-commit:
    uses: coatl-dev/workflows/.github/workflows/pre-commit.yml@8d3c0aba2a053986bce9382063facccf1fd98247 # v7.0.0
    with:
      checkout-ref: ${{ github.ref }}
      skip-hooks: 'pylint'

  pylint:
    uses: coatl-dev/workflows/.github/workflows/pylint.yml@3b10e4c46730151093c7ccbc52fd689a48b94726 # v7.0.16
    with:
      path: src
      checkout-ref: ${{ github.ref }}

  tox:
    if: ${{ github.event_name == 'pull_request' }}
    uses: $/.github/workflows/tox.yml
    with:
      checkout-ref: ${{ github.ref }}
