name: ci

on:
  push:
    branches:
      - '8.1'
  pull_request:
    branches:
      - '8.1'

jobs:
  pre-commit:
    uses: coatl-dev/workflows/.github/workflows/pre-commit.yml@8d3c0aba2a053986bce9382063facccf1fd98247 # v7.0.0
    with:
      checkout-ref: ${{ github.ref }}
      skip-hooks: 'pylint'

  pylint:
    uses: coatl-dev/workflows/.github/workflows/pylint.yml@ac7772bd171c548f66cbd19be77872dfd6e326ce # v7.0.24
    with:
      path: src
      checkout-ref: ${{ github.ref }}

  tox:
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/tox.yml
    with:
      checkout-ref: ${{ github.ref }}
