name: pre-commit-autoupdate

on:
  schedule:
    - cron: '0 20 1 * *'
  workflow_dispatch:

jobs:
  pre-commit-autoupdate:
    strategy:
      matrix:
        branch: ['8.1', '8.3']
      fail-fast: false
    uses: coatl-dev/workflows/.github/workflows/pre-commit-autoupdate.yml@0d24a98543a7e17f432503425e6ef836972864bb # v7.0.28
    with:
      autoupdate-branch:  '${{ matrix.branch }}'
      checkout-ref: ${{ matrix.branch }}
      pr-branch: ${{ matrix.branch }}-coatl-dev-pre-commit-autoupdate
    secrets:
      gh-token: ${{ secrets.COATL_BOT_GH_TOKEN }}
      gpg-sign-passphrase: ${{ secrets.COATL_BOT_GPG_PASSPHRASE }}
      gpg-sign-private-key: ${{ secrets.COATL_BOT_GPG_PRIVATE_KEY }}
