name: publish

on:
  release:
    types: [published]

jobs:
  tox-package:
    uses: coatl-dev/workflows/.github/workflows/tox-docker.yml@v6
    with:
      checkout-ref: ${{ github.event.release.tag_name }}

  tox-stubs:
    uses: coatl-dev/workflows/.github/workflows/tox.yml@v6
    with:
      python-versions: |
        3.9
        3.10
        3.11
        3.12
      working-directory: stubs
      checkout-ref: ${{ github.event.release.tag_name }}

  pypi-upload:
    needs: [tox-package, tox-stubs]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Upload package to PyPI
        uses: coatl-dev/actions/pypi-upload@v5
        with:
          password: ${{ secrets.PYPI_API_TOKEN_IGNITION_API_PKG }}

      - name: Upload stubs to PyPI
        uses: coatl-dev/actions/pypi-upload@v5
        with:
          python-version: '3.12'
          password: ${{ secrets.PYPI_API_TOKEN_IGNITION_API_STUBS }}
          working-directory: stubs
